version: "3.1"
services:
  prlmtq_frontend:
    image: node:latest
    container_name: prlmtq_frontend
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/frontend
    working_dir: /usr/src/frontend
    command: npm run dev